/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escuelasockets.GUI;


import escuelasockets.Schelude;
import escuelasockets.SchoolClient;
import escuelasockets.Student;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Absalom Herrera
 */
public class EnrollmentGUI extends javax.swing.JFrame {

    
    private Student s;
    private List l;
    /**
     * Creates new form EnrollmentGUI
     */
    
    public EnrollmentGUI(Student s, List l) {
        this.s = s;
        this.l = l;
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        DefaultTableModel model = (DefaultTableModel) tableEnrollment.getModel();
        for (int i = 0; i < l.size(); i++) {
            Schelude sche = (Schelude) l.get(i);
            model.addRow(new Object[]{sche.getIdSchelude(), sche.getCourseName(), sche.getProfessorName() + " " + sche.getProfessorLastName(), sche.getDay1(), sche.getDay2(), sche.getDay3(), sche.getDay4(), sche.getDay5()});
        }
        //tableEnrollment.setPreferredScrollableViewportSize(tableEnrollment.getPreferredSize());
        //this.repaint();
        tableEnrollment.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablePane = new javax.swing.JScrollPane();
        tableEnrollment = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        enrollButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablePane.setPreferredSize(tableEnrollment.getPreferredSize());

        tableEnrollment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Group", "Course", "Professor", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePane.setViewportView(tableEnrollment);
        if (tableEnrollment.getColumnModel().getColumnCount() > 0) {
            tableEnrollment.getColumnModel().getColumn(0).setResizable(false);
            tableEnrollment.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableEnrollment.getColumnModel().getColumn(1).setResizable(false);
            tableEnrollment.getColumnModel().getColumn(1).setPreferredWidth(300);
            tableEnrollment.getColumnModel().getColumn(2).setResizable(false);
            tableEnrollment.getColumnModel().getColumn(2).setPreferredWidth(150);
            tableEnrollment.getColumnModel().getColumn(3).setResizable(false);
            tableEnrollment.getColumnModel().getColumn(3).setPreferredWidth(50);
            tableEnrollment.getColumnModel().getColumn(4).setResizable(false);
            tableEnrollment.getColumnModel().getColumn(4).setPreferredWidth(50);
            tableEnrollment.getColumnModel().getColumn(5).setResizable(false);
            tableEnrollment.getColumnModel().getColumn(5).setPreferredWidth(50);
            tableEnrollment.getColumnModel().getColumn(6).setResizable(false);
            tableEnrollment.getColumnModel().getColumn(6).setPreferredWidth(50);
            tableEnrollment.getColumnModel().getColumn(7).setResizable(false);
            tableEnrollment.getColumnModel().getColumn(7).setPreferredWidth(50);
        }

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        enrollButton.setText("Enroll Course");
        enrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(tablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(enrollButton)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(18, 18, 18)
                .addComponent(tablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(enrollButton)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        IndexStudent is = new IndexStudent(s);
        is.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void enrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollButtonActionPerformed
        int rowIndex = tableEnrollment.getSelectedRow();
        Schelude sch = new Schelude();
        sch.setIdSchelude((int) tableEnrollment.getValueAt(rowIndex, 0));
        sch.setCourseName((String) tableEnrollment.getValueAt(rowIndex, 1));
        sch.setProfessorName((String) tableEnrollment.getValueAt(rowIndex, 2));
        sch.setDay1((String) tableEnrollment.getValueAt(rowIndex, 3));
        sch.setDay2((String) tableEnrollment.getValueAt(rowIndex, 4));
        sch.setDay3((String) tableEnrollment.getValueAt(rowIndex, 5));
        sch.setDay4((String) tableEnrollment.getValueAt(rowIndex, 6));
        sch.setDay5((String) tableEnrollment.getValueAt(rowIndex, 7));
        SchoolClient c = new SchoolClient();
        int res = c.enrollStudent(s, sch);
        if (res == 0){
            JOptionPane.showMessageDialog(null, "Enrollment of " + sch.getCourseName() +" completed");
            ((DefaultTableModel)tableEnrollment.getModel()).removeRow(rowIndex);
        }
        System.out.println(sch.toString());
    }//GEN-LAST:event_enrollButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton enrollButton;
    private javax.swing.JTable tableEnrollment;
    private javax.swing.JScrollPane tablePane;
    // End of variables declaration//GEN-END:variables
}
