/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escuelasockets.GUI;

import escuelasockets.Schelude;
import escuelasockets.Student;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Absalom Herrera
 */
public class ScheludeGUI extends javax.swing.JFrame {

    private Student s;
    private List l;
    /**
     * Creates new form ScheludeGUI
     */
    public ScheludeGUI(Student s, List l) {
        this.s = s;
        this.l = l;
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        DefaultTableModel model = (DefaultTableModel) tableSchelude.getModel();
        for (int i = 0; i < l.size(); i++) {
            Schelude sche = (Schelude) l.get(i);
            model.addRow(new Object[]{sche.getIdSchelude(), sche.getCourseName(), sche.getProfessorName() + " " + sche.getProfessorLastName(), sche.getDay1(), sche.getDay2(), sche.getDay3(), sche.getDay4(), sche.getDay5()});
        }
        //tableEnrollment.setPreferredScrollableViewportSize(tableEnrollment.getPreferredSize());
        //this.repaint();
        tableSchelude.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        welcomeLabel.setText(welcomeLabel.getText() + " " + s.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablePane = new javax.swing.JScrollPane();
        tableSchelude = new javax.swing.JTable();
        welcomeLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablePane.setPreferredSize(tableSchelude.getPreferredSize());

        tableSchelude.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Group", "Course", "Professor", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePane.setViewportView(tableSchelude);
        if (tableSchelude.getColumnModel().getColumnCount() > 0) {
            tableSchelude.getColumnModel().getColumn(0).setResizable(false);
            tableSchelude.getColumnModel().getColumn(1).setResizable(false);
            tableSchelude.getColumnModel().getColumn(1).setPreferredWidth(250);
            tableSchelude.getColumnModel().getColumn(2).setResizable(false);
            tableSchelude.getColumnModel().getColumn(4).setResizable(false);
            tableSchelude.getColumnModel().getColumn(6).setResizable(false);
            tableSchelude.getColumnModel().getColumn(7).setResizable(false);
        }

        welcomeLabel.setText("Schelude for:");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(welcomeLabel)
                    .addComponent(tablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcomeLabel)
                .addGap(32, 32, 32)
                .addComponent(tablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        IndexStudent is = new IndexStudent(s);
        is.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane tablePane;
    private javax.swing.JTable tableSchelude;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
